### ISSUE TITLE
代码中文件夹错误导致的问题和一些建议

### ISSUE THREAD

**Issue by ColorfulSS** [IKAROS93/Livox_laser_simulation_for_CARLA#1]
非常感谢carla模拟livox的开源工作，嘻嘻，大佬很强！
我在动手编译自己的Carla 0.9.12的时候遇到了问题以及一些疑惑，导致编译过程报错，或者运行时无法模拟Livox。经过一天的问题原因的定位，问题如下，希望能为后来的同学提供一些小建议：

1. LibCarla中的s11文件夹应该修改为s11n文件夹
<img width="643" alt="image" src="https://user-images.githubusercontent.com/52792433/179550761-ba9a3301-5822-4b04-8f8c-5495ba72d741.png">

2. 拷贝LivoxLaserCsv文件夹后需要修改文件夹名称为LivoxCsv
- Github文件夹：
<img width="876" alt="image" src="https://user-images.githubusercontent.com/52792433/179551178-6ef78fb0-bd88-4206-a960-3687d4abd676.png">

- 代码中需要的文件夹名称
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/52792433/179550930-8a34fabc-ea4f-4b6c-9915-0030046fb085.png">

**Comment by IKAROS93** [comment]
多谢指正，已经修改
