### ISSUE TITLE
Error while using the Livox lidars

### ISSUE THREAD

**Issue by kovendijozsef** [IKAROS93/Livox_laser_simulation_for_CARLA#12]
Hi!

I am creating this issue for anyone who runs into the same errors as I did when using the different Livox lidars.
For some reason in the 
`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp `
file the csv was not read in correctly and either no points were captured or got the following error message:

> RuntimeError: rpc::rpc_error during call in function spawn_actor_with_parent

The solution to this problems is to change the body of the loop in line [469 ](https://github.com/IKAROS93/Livox_laser_simulation_for_CARLA/blob/8d042ce0aefd1db06eff554fa55bc9d1697f1335/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp#L469) to 

```
{
    char* endPtr; // Pointer to the character that ends the conversion
    float floatValue = std::strtof(str.c_str(), &endPtr);
    // Check if the conversion was successful
    if (endPtr != str.c_str()) {
	lineArray.push_back(floatValue);
    }
}

```

**Comment by qzhq747** [comment]
I face the same issue. Solve it with your solution. THANKS a lot.
