### ISSUE TITLE
error in lidar type

### ISSUE THREAD

**Issue by ShiJian1995** [IKAROS93/Livox_laser_simulation_for_CARLA#5]
hello, i meet a problem, when i change the lidar type the 1 or 2, the terminal will print :[ERROR] [1678867997.660690, 3.882352]: Sensor sensor.lidar.ray_cast_livox/livox_lidar will not be spawned: rpc::rpc_error during call in function spawn_actor_with_parent. Did you meet this? And another question, how did you set the IMU frequency to 100Hz to run the lio algorithm?

**Comment by IKAROS93** [comment]
1. Sorry I haven't meet the 1st problem ; 2. Set the IMU frequency in config file

**Comment by ShiJian1995** [comment]
> 1. Sorry I haven't meet the 1st problem ; 2. Set the IMU frequency in config file

thanks for your replay.

**Comment by matejm42** [comment]
> hello, i meet a problem, when i change the lidar type the 1 or 2, the terminal will print :[ERROR] [1678867997.660690, 3.882352]: Sensor sensor.lidar.ray_cast_livox/livox_lidar will not be spawned: rpc::rpc_error during call in function spawn_actor_with_parent. Did you meet this? And another question, how did you set the IMU frequency to 100Hz to run the lio algorithm?

It does the same to me (Carla 0.9.13).

I also tried to switch the numbers of the types in [RayCastSemanticLidar.cpp](https://github.com/IKAROS93/Livox_laser_simulation_for_CARLA/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp) file but didn't help. So the problem is not in reading nonzero values. 

If I am not mistaken, the only part where types are different are values read from CSV, so it's strange that only horizon is working.

**Comment by IKAROS93** [comment]
> > hello, i meet a problem, when i change the lidar type the 1 or 2, the terminal will print :[ERROR] [1678867997.660690, 3.882352]: Sensor sensor.lidar.ray_cast_livox/livox_lidar will not be spawned: rpc::rpc_error during call in function spawn_actor_with_parent. Did you meet this? And another question, how did you set the IMU frequency to 100Hz to run the lio algorithm?
> 
> It does the same to me (Carla 0.9.13).
> 
> I also tried to switch the numbers of the types in [RayCastSemanticLidar.cpp](https://github.com/IKAROS93/Livox_laser_simulation_for_CARLA/blob/master/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/RayCastSemanticLidar.cpp) file but didn't help. So the problem is not in reading nonzero values.
> 
> If I am not mistaken, the only part where types are different are values read from CSV, so it's strange that only horizon is working.

It may be the Character encoding problem. You can try to overwrite the data of other lidar models with that of Horizon to see if it works normally

**Comment by ElizabethSF** [comment]
I met the same problem 2. And I found that the problem can be solved by deleting the first line in 'avia.csv'. See for yourself~
