### ISSUE TITLE
Source code of CARLA simulator and CARLA-ROS Bridge with implemented Livox

### ISSUE THREAD

**Issue by matejm42** [IKAROS93/Livox_laser_simulation_for_CARLA#7]
If it helps someone I published forks of CARLA repositories with this implementation of Livox lidar.

I merged your code with CARLA 0.9.13 and included horizon.csv, so the configuration file is not needed: [https://github.com/matejm42/carla/tree/0.9.13-livox](https://github.com/matejm42/carla/tree/0.9.13-livox)

and merged your code with CARLA-ROS bridge:
[https://github.com/matejm42/ros-bridge/tree/0.9.13-livox](https://github.com/matejm42/ros-bridge/tree/0.9.13-livox)

**Comment by IKAROS93** [comment]
thanks for your working!
